### ISSUE TITLE
css를 초기화 하자! (CSS reset)

### ISSUE THREAD

**Issue by leejanghe** [leejanghe/paint#2]
## CSS reset

웹 브라우저 저마다 기본 스타일을 가지고 있다. 따라서 스타일을 지정하지 않아도 html 태그에 따라 다른 모양으로 웹 브라우저에 표현된다. 그런데 기본 스타일이 웹 브라우저마다 조금씩 차이가 나서 CSS를 초기화 시킵니다. 쉽게 말해 웹 브라우저의 기본 스타일 시트의 설정을 '모양없음'으로 바꾸는 것을 의미합니다.

[참고사이트](https://meyerweb.com/eric/tools/css/reset/)

## 사용 방법

reset파일을 만들고 위에 사이트 링크에 가서 아래의 코드를 복붙합니다.

```css
/* reset.css */
html, body, div, span, applet, object, iframe,
h1, h2, h3, h4, h5, h6, p, blockquote, pre,
a, abbr, acronym, address, big, cite, code,
del, dfn, em, img, ins, kbd, q, s, samp,
small, strike, strong, sub, sup, tt, var,
b, u, i, center,
dl, dt, dd, ol, ul, li,
fieldset, form, label, legend,
table, caption, tbody, tfoot, thead, tr, th, td,
article, aside, canvas, details, embed, 
figure, figcaption, footer, header, hgroup, 
menu, nav, output, ruby, section, summary,
time, mark, audio, video {
	margin: 0;
	padding: 0;
	border: 0;
	font-size: 100%;
	font: inherit;
	vertical-align: baseline;
}
/* HTML5 display-role reset for older browsers */
article, aside, details, figcaption, figure, 
footer, header, hgroup, menu, nav, section {
	display: block;
}
body {
	line-height: 1;
}
ol, ul {
	list-style: none;
}
blockquote, q {
	quotes: none;
}
blockquote:before, blockquote:after,
q:before, q:after {
	content: '';
	content: none;
}
table {
	border-collapse: collapse;
	border-spacing: 0;
}
```

그다음 메인 css에 @import를 사용합니다.

```css
@import reset.css";

```
